// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
// This file is autogenerated by ./scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"
import { RegistryIndex } from "../lib/schema"

export const index: RegistryIndex = {
  "example-forms": {
    name: "example-forms",
    title: "Next.js + Forms",
    description: "Server actions and Zod validation.",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{"path":"example-forms/app/page.tsx","type":"registry:page","target":"app/page.tsx"},{"path":"example-forms/app/layout.tsx","type":"registry:page","target":"app/layout.tsx"},{"path":"example-forms/components/contact-form.tsx","type":"registry:component"},{"path":"example-forms/lib/actions.ts","type":"registry:lib"},{"path":"example-forms/lib/schema.ts","type":"registry:lib"}],
    meta: {
      
      component: React.lazy(() => import("app/registry/example-forms/app/page.tsx")),
    },
  },
  "example-login": {
    name: "example-login",
    title: "Login form with Apple and Google auth",
    description: "A single-page login form made with shadcn/ui.",
    type: "registry:block",
    registryDependencies: ["button","input"],
    files: [{"path":"example-login/app/page.tsx","type":"registry:page","target":"app/page.tsx"},{"path":"example-login/app/layout.tsx","type":"registry:page","target":"app/layout.tsx"},{"path":"example-login/app/globals.css","type":"registry:page","target":"app/globals.css"},{"path":"example-login/components/login-form.tsx","type":"registry:component"}],
    meta: {
      
      component: React.lazy(() => import("app/registry/example-login/app/page.tsx")),
    },
  },
  "example-chatbot": {
    name: "example-chatbot",
    title: "OpenAI and AI SDK Chatbot",
    description: "Chatbot built using the AI SDK and gpt-4o-mini.",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{"path":"example-chatbot/page.tsx","type":"registry:page","target":"app/page.tsx"},{"path":"example-chatbot/layout.tsx","type":"registry:page","target":"app/layout.tsx"},{"path":"example-chatbot/components/chat-form.tsx","type":"registry:component"},{"path":"example-chatbot/components/autoresize-textarea.tsx","type":"registry:component"},{"path":"example-chatbot/api/chat/route.ts","type":"registry:page","target":"app/api/chat/route.ts"}],
    meta: {
      ...{"env":[{"name":"OPENAI_API_KEY","url":"https://platform.openai.com/api-keys"}]},
      component: React.lazy(() => import("app/registry/example-chatbot/page.tsx")),
    },
  },
}
