// eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-nocheck
    // This file is autogenerated by ./scripts/build-v0-registry.ts
    // Do not edit this file directly.
    import * as React from "react"
    import { RegistryIndex } from "../lib/schema"

    export const index: RegistryIndex = {
"action-button-template": {
  "name": "action-button-template",
  "title": "Action Button Template",
  "description": "A template for action-button-template",
  "type": "registry:block",
  "files": [
    {
      "path": "action-button-template/app/page.tsx",
      "type": "registry:page",
      "target": "app/page.tsx"
    },
    {
      "path": "action-button-template/app/layout.tsx",
      "type": "registry:page",
      "target": "app/layout.tsx"
    },
    {
      "path": "action-button-template/app/globals.css",
      "type": "registry:page",
      "target": "app/globals.css"
    },
    {
      "path": "action-button-template/app/component/action-button.tsx",
      "type": "registry:page",
      "target": "app/component/action-button.tsx"
    }
  ],
  "meta": {
    "component": "React.lazy(() => import(\"app/registry/action-button-template/app/page.tsx\"))"
  }
},
"display-cards-template": {
  "name": "display-cards-template",
  "title": "Display Cards Template",
  "description": "A template for display-cards-template",
  "type": "registry:block",
  "files": [
    {
      "path": "display-cards-template/app/page.tsx",
      "type": "registry:page",
      "target": "app/page.tsx"
    },
    {
      "path": "display-cards-template/app/layout.tsx",
      "type": "registry:page",
      "target": "app/layout.tsx"
    },
    {
      "path": "display-cards-template/app/globals.css",
      "type": "registry:page",
      "target": "app/globals.css"
    },
    {
      "path": "display-cards-template/app/component/display-cards.tsx",
      "type": "registry:page",
      "target": "app/component/display-cards.tsx"
    }
  ],
  "meta": {
    "component": "React.lazy(() => import(\"app/registry/display-cards-template/app/page.tsx\"))"
  }
},
"expandable-card-template": {
  "name": "expandable-card-template",
  "title": "Expandable Card Template",
  "description": "A template for expandable-card-template",
  "type": "registry:block",
  "files": [
    {
      "path": "expandable-card-template/app/page.tsx",
      "type": "registry:page",
      "target": "app/page.tsx"
    },
    {
      "path": "expandable-card-template/app/layout.tsx",
      "type": "registry:page",
      "target": "app/layout.tsx"
    },
    {
      "path": "expandable-card-template/app/globals.css",
      "type": "registry:page",
      "target": "app/globals.css"
    },
    {
      "path": "expandable-card-template/app/component/expandable-card.tsx",
      "type": "registry:page",
      "target": "app/component/expandable-card.tsx"
    },
    {
      "path": "expandable-card-template/app/hooks/use-expandable.ts",
      "type": "registry:page",
      "target": "app/hooks/use-expandable.ts"
    }
  ],
  "meta": {
    "component": "React.lazy(() => import(\"app/registry/expandable-card-template/app/page.tsx\"))"
  }
},
"floating-action-panel-template": {
  "name": "floating-action-panel-template",
  "title": "Floating Action Panel Template",
  "description": "A template for floating-action-panel-template",
  "type": "registry:block",
  "files": [
    {
      "path": "floating-action-panel-template/app/page.tsx",
      "type": "registry:page",
      "target": "app/page.tsx"
    },
    {
      "path": "floating-action-panel-template/app/layout.tsx",
      "type": "registry:page",
      "target": "app/layout.tsx"
    },
    {
      "path": "floating-action-panel-template/app/globals.css",
      "type": "registry:page",
      "target": "app/globals.css"
    },
    {
      "path": "floating-action-panel-template/app/component/floating-action-panel.tsx",
      "type": "registry:page",
      "target": "app/component/floating-action-panel.tsx"
    }
  ],
  "meta": {
    "component": "React.lazy(() => import(\"app/registry/floating-action-panel-template/app/page.tsx\"))"
  }
},
"hero-badge-template": {
  "name": "hero-badge-template",
  "title": "Hero Badge Template",
  "description": "A template for hero-badge-template",
  "type": "registry:block",
  "files": [
    {
      "path": "hero-badge-template/app/page.tsx",
      "type": "registry:page",
      "target": "app/page.tsx"
    },
    {
      "path": "hero-badge-template/app/layout.tsx",
      "type": "registry:page",
      "target": "app/layout.tsx"
    },
    {
      "path": "hero-badge-template/app/globals.css",
      "type": "registry:page",
      "target": "app/globals.css"
    },
    {
      "path": "hero-badge-template/app/component/hero-badge.tsx",
      "type": "registry:page",
      "target": "app/component/hero-badge.tsx"
    }
  ],
  "meta": {
    "component": "React.lazy(() => import(\"app/registry/hero-badge-template/app/page.tsx\"))"
  }
},
"hero-template": {
  "name": "hero-template",
  "title": "Hero Template",
  "description": "A template for hero-template",
  "type": "registry:block",
  "files": [
    {
      "path": "hero-template/app/page.tsx",
      "type": "registry:page",
      "target": "app/page.tsx"
    },
    {
      "path": "hero-template/app/layout.tsx",
      "type": "registry:page",
      "target": "app/layout.tsx"
    },
    {
      "path": "hero-template/app/globals.css",
      "type": "registry:page",
      "target": "app/globals.css"
    },
    {
      "path": "hero-template/app/component/expandable-card.tsx",
      "type": "registry:page",
      "target": "app/component/expandable-card.tsx"
    },
    {
      "path": "hero-template/app/component/hero.tsx",
      "type": "registry:page",
      "target": "app/component/hero.tsx"
    }
  ],
  "meta": {
    "component": "React.lazy(() => import(\"app/registry/hero-template/app/page.tsx\"))"
  }
},
"landing-page-test": {
  "name": "landing-page-test",
  "title": "Landing Page Test",
  "description": "A template for landing-page-test",
  "type": "registry:block",
  "files": [
    {
      "path": "landing-page-test/app/page.tsx",
      "type": "registry:page",
      "target": "app/page.tsx"
    },
    {
      "path": "landing-page-test/app/layout.tsx",
      "type": "registry:page",
      "target": "app/layout.tsx"
    },
    {
      "path": "landing-page-test/app/globals.css",
      "type": "registry:page",
      "target": "app/globals.css"
    }
  ],
  "meta": {
    "component": "React.lazy(() => import(\"app/registry/landing-page-test/app/page.tsx\"))"
  }
},
"popover-template": {
  "name": "popover-template",
  "title": "Popover Template",
  "description": "A template for popover-template",
  "type": "registry:block",
  "files": [
    {
      "path": "popover-template/app/page.tsx",
      "type": "registry:page",
      "target": "app/page.tsx"
    },
    {
      "path": "popover-template/app/layout.tsx",
      "type": "registry:page",
      "target": "app/layout.tsx"
    },
    {
      "path": "popover-template/app/globals.css",
      "type": "registry:page",
      "target": "app/globals.css"
    },
    {
      "path": "popover-template/app/component/popover.tsx",
      "type": "registry:page",
      "target": "app/component/popover.tsx"
    }
  ],
  "meta": {
    "component": "React.lazy(() => import(\"app/registry/popover-template/app/page.tsx\"))"
  }
},
"tweet-card-template": {
  "name": "tweet-card-template",
  "title": "Tweet Card Template",
  "description": "A template for tweet-card-template",
  "type": "registry:block",
  "files": [
    {
      "path": "tweet-card-template/app/page.tsx",
      "type": "registry:page",
      "target": "app/page.tsx"
    },
    {
      "path": "tweet-card-template/app/globals.css",
      "type": "registry:page",
      "target": "app/globals.css"
    }
  ],
  "meta": {
    "component": "React.lazy(() => import(\"app/registry/tweet-card-template/app/page.tsx\"))"
  }
}
}